### ISSUE TITLE
Plugin incompatble with "instant images" plugin

### ISSUE THREAD

**Issue by oferlaor** [mcguffin/the-paste#40] opened 2023-08-04 16:13 UTC
I patched it by wrapping this code with a try/catch:
```                 
               this.controller instanceof wp.media.view.MediaFrame.Select || wp.media.thepaste.supports.paste && (e = new wp.media.view.Button({
                            text: n.copy_paste,
                            className: "grabber-button",
                            priority: -64,
                            click: function () {
                                t.thepaste.active = t.thepaste.paste,
                                t.thepasteOpen(n.copy_paste)
                            }
                        }), this.thepaste.paste.grabber = new wp.media.thepaste.view.DataSourceImageGrabber({
                            controller: this.controller,
                            grabber: wp.media.thepaste.view.Pasteboard,
                            wpuploader: this.controller.uploader.uploader.uploader
                        }), this.toolbar.set("pasteModeButton", e.render()))
```

Here is the patched code:
```					
                       ( function () {
						try {
							return this.controller instanceof wp.media.view.MediaFrame.Select || wp.media.thepaste.supports.paste && (e = new wp.media.view.Button({
								text: n.copy_paste,
								className: "grabber-button",
								priority: -64,
								click: function () {
									t.thepaste.active = t.thepaste.paste,
									t.thepasteOpen(n.copy_paste)
								}
							}), this.thepaste.paste.grabber = new wp.media.thepaste.view.DataSourceImageGrabber({
								controller: this.controller,
								grabber: wp.media.thepaste.view.Pasteboard,
								wpuploader: this.controller.uploader.uploader.uploader
							}), this.toolbar.set("pasteModeButton", e.render()))
						} catch (e) {
							return null;
						}
					})
```

**Comment by mcguffin** [comment] 2023-09-23 11:15
Sorry … I can't reproduce this.
What exactly are you are doing?

**Comment by oferlaor** [comment] 2023-09-23 13:03
> Sorry … I can't reproduce this.
> 
> What exactly are you are doing?

Install the plugin "instant images" in addition to the-paste. 

Now open a post. Press insert media button and see that you get a console error.

**Comment by oferlaor** [comment] 2023-09-23 19:19
![the paste 1](https://github.com/mcguffin/the-paste/assets/3070108/751ff875-ec9f-43cc-966e-21c5e2167ed1)
You can see that "the paste" competes with instant images (https://wordpress.org/plugins/instant-images/) on the top button on the Add Media screen.

![the paste 2](https://github.com/mcguffin/the-paste/assets/3070108/46c3cc1c-4cfa-4b73-b51a-613e4682dd8a)
When both are present, going into the classic editor and pressing Add Media produces this error.
![the paste 3](https://github.com/mcguffin/the-paste/assets/3070108/21ea186a-c7d3-4593-a6f2-04e9366e9b4d)

**Comment by mcguffin** [comment] 2023-09-24 14:40
Thanks! I can see: the Copy & Paste Tab is missing in the media library...
I just released Version 2, bringing a revised UX concept and rewritten JS. No issues with Instant Images encountered so far...
Fell free to close the issue, if it is fixed for you (or to come back if not).

**Comment by oferlaor** [comment] 2023-09-25 06:10
I can't install version 2.0.1, getting this error:

```
wp-tinymce.js?ver=49110-20201110:3 Failed to initialize plugin: the_paste TypeError: Cannot read properties of undefined (reading 'options')
    at new n (the-paste-plugin.js?wp-mce-49110-20201110-tadv-5900:1:519)
    at Ew (wp-tinymce.js?ver=49110-20201110:3:330473)
    at Array.<anonymous> (wp-tinymce.js?ver=49110-20201110:3:332223)
    at Object.jt [as each] (wp-tinymce.js?ver=49110-20201110:3:29356)
    at Aw (wp-tinymce.js?ver=49110-20201110:3:332173)
    at tN.<anonymous> (wp-tinymce.js?ver=49110-20201110:3:333551)
    at Array.<anonymous> (wp-tinymce.js?ver=49110-20201110:3:96969)
    at jt (wp-tinymce.js?ver=49110-20201110:3:29356)
    at u (wp-tinymce.js?ver=49110-20201110:3:96914)
    at n (wp-tinymce.js?ver=49110-20201110:3:96402)
```

**Comment by mcguffin** [comment] 2023-09-27 10:58
@see #45

**Closed by mcguffin** 2023-09-27 10:58 UTC
